# Generated by Django 5.0.6 on 2024-05-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatTurkishApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopularDish',
            new_name='PopularDishes',
        ),
    ]
