# Generated by Django 5.0.6 on 2024-05-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatTurkishApi', '0004_news_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
