# Generated by Django 5.0.6 on 2024-05-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatTurkishApi', '0005_alter_testimony_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populardishes',
            name='price',
            field=models.FloatField(),
        ),
    ]
