# Generated by Django 5.0.6 on 2024-05-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatTurkishApi', '0008_sendmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
